ERROR REPORT DATETIME 2021-06-29 14:54:07.727876-------------------- ERROR IN FILE 96449_doc20210105094602172380 --------------------
[<FrameSummary file C:/Users/Utente/Documents/Multitraccia/Progetti/Cobat/OCR_development/NEW_OCR/main_OCR.py, line 1245 in <module>>, <FrameSummary file C:/Users/Utente/Documents/Multitraccia/Progetti/Cobat/OCR_development/NEW_OCR/main_OCR.py, line 121 in get_dataframe>, <FrameSummary file C:\Users\Utente\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\generic.py, line 5877 in astype>, <FrameSummary file C:\Users\Utente\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\internals\managers.py, line 631 in astype>, <FrameSummary file C:\Users\Utente\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\internals\managers.py, line 427 in apply>, <FrameSummary file C:\Users\Utente\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\internals\blocks.py, line 673 in astype>, <FrameSummary file C:\Users\Utente\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\dtypes\cast.py, line 1068 in astype_nansafe>]
Exception - Cannot convert non-finite values (NA or inf) to integer
